# Generated by Django 5.0.6 on 2024-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], max_length=20)),
                ('profile_pic', models.ImageField(upload_to='profiles/')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
